[[plugins]]
repo = 'vimwiki/vimwiki'
hook_add = 'source ~/.vim/plugins/vimwiki.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.vim/plugins/nerdtree.vim'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
    colorscheme gruvbox
    set background=dark
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source ~/.vim/plugins/indentLine.vim'

[[plugins]]
repo = 'Chiel92/vim-autoformat'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo =  'vim-airline/vim-airline'

[[plugins]]
repo =  'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'easymotion/vim-easymotion'
