
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.vim/plugins/nerdtree.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
